/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/foldable_paper.glb -s 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/foldable_paper.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Middle.geometry} material={materials['Material.001']} scale={[0.86, 0.005, 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Bottom.geometry} material={materials['Material.001']} position={[0.86, -0.005, 0]} scale={[0.86, 0.005, 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Top.geometry} material={materials['Material.001']} position={[-0.86, -0.005, 0]} scale={[0.86, 0.005, 2]} />
    </group>
  )
}

useGLTF.preload('/foldable_paper.glb')
