/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/mailbox.glb -s 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mailbox.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[0, 7.101, 0]} scale={[1.717, 1.717, 3.74]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[0, 5.465, 3.735]} scale={[1.636, 1.636, 3.564]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0, 5.465, 3.735]} rotation={[0, 0, -Math.PI / 2]} scale={[0.071, 1.479, 0.071]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[1.773, 7.092, 1.554]} rotation={[-Math.PI, 0, 0]} scale={[-0.047, -1.247, -0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[0, 1.684, 0]} scale={[0.324, 3.792, 0.324]} />
    </group>
  )
}

useGLTF.preload('/mailbox.glb')
