/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/foldable_paper.glb -s 
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, animated, config } from '@react-spring/three'

export function FoldablePaper(props) {
  const { nodes, materials } = useGLTF('./models/foldable_paper.glb')
  const { open } = props;
  const [prevOpen, setPrev] = useState(false);

  const [{ topFold, bottomFold }, setFlap] = useSpring(() => ({
    topFold: [0, 0, Math.PI],
    bottomFold: [0, 0, -Math.PI]
  }))

  useEffect(() => {
    if (open) {
      setFlap.start({
        from: {
          topFold: [0, 0, Math.PI],
          bottomFold: [0, 0, -Math.PI],
        },
        to: [
          {
            bottomFold: [0, 0, 0],
            delay: 1700
          },
          {
            topFold: [0, 0, 0],
          }
        ]
      })
      setPrev(open);
    } else if (!open && prevOpen) {
      setFlap.start({
        from: {
          topFold: [0, 0, 0],
          bottomFold: [0, 0, 0],
        },
        to: [
          {
            topFold: [0, 0, Math.PI],
          },
          {
            bottomFold: [0, 0, -Math.PI],
          }
        ]
      })
      setPrev(open);
    }
  }, [open])

  return (
    <group {...props} dispose={null}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Middle.geometry}
      material={materials['Material.001']}
      scale={[0.86, 0.005, 2]}
    />
    <animated.mesh
      castShadow
      receiveShadow
      geometry={nodes.Top.geometry}
      material={materials['Material.001']}
      position={[-0.86, -0.005, 0]}
      scale={[0.86, 0.005, 2]}
      rotation={topFold}
    />
    <animated.mesh
      castShadow
      receiveShadow
      geometry={nodes.Bottom.geometry}
      material={materials['Material.001']}
      position={[0.86, -0.005, 0]}
      scale={[0.86, 0.005, 2]}
      rotation={bottomFold}
    />
  </group>
  )
}

useGLTF.preload('./models/foldable_paper.glb')
